name: wtr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.20
  - scipy>=1.7
  - pandas>=1.3
  - matplotlib>=3.4
  - scikit-learn>=1.0
  - pydantic>=1.10
  - pyyaml>=5.4
  - networkx>=2.6
  - typer>=0.6
  - ase>=3.25
  - xtb  # provides the xtb binary used by ase.calculators.xtb
  - libxc
  - tblite
  - pip:
      - .
